name: Publish Docker Image

on:
  push:
    branches:
      - develop
  release:
    types:
      - published

jobs:
  push:
    name: Push Image to GitHub Packages
    runs-on: ubuntu-20.04
    # Always run against a tag, even if the commit into the tag has [docker skip]
    # within the commit message.
    if: "!contains(github.ref, 'develop') || (!contains(github.event.head_commit.message, 'skip docker') && !contains(github.event.head_commit.message, 'docker skip'))"
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/pterodactyl-china/panel
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'release' && github.event.action == 'published' && github.event.release.prerelease == false }}
            type=ref,event=tag
            type=ref,event=branch

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Update app.php version
        if: "github.event_name == 'release' && github.event.action == 'published'"
        run: |
          sed -i "s/    'version' => 'canary',/    'version' => '${REF:11}',/" config/app.php

      - name: Build and Push (tag)
        uses: docker/build-push-action@v3
        if: "github.event_name == 'release' && github.event.action == 'published'"
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: ${{ steps.docker_meta.outputs.tags }}

      - name: Build and Push (develop)
        uses: docker/build-push-action@v3
        if: "github.event_name == 'push' && contains(github.ref, 'develop')"
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
